### ISSUE TITLE
error: duplicate ‘inline’

### ISSUE THREAD

**Issue by xiota** [cemu-project/Cemu#1472]
### Current Behavior

Attempt to build 8dd809d with GCC 14.2.1 fails.  Last successful build was f61539a.  Problem appears to have been introduced in 8dd809d. 
```
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1

/home/builder/build/src/cemu/src/Common/precompiled.h:284:14: error: duplicate ‘inline’
  284 | FORCE_INLINE inline int BSF(uint32 v) // returns index of first bit set, counting from LSB. If v is 0 then result is undefined
      |              ^~~~~~
      |              ------
```

Relevant file and lines:

https://github.com/cemu-project/Cemu/blob/0a5908502147c9d35189bdbfe38ba6d5bebd0f76/src/Common/precompiled.h#L277-L285

### Expected Behavior

Should compile successfully.

### Steps to Reproduce

Clone repo and attempt build using previously working method.

### System Info (Optional)

OS: Arch Linux
GPU: N/A

### Emulation Settings (Optional)

N/A

### Logs (Optional)

N/A

**Comment by Exzap** [comment]
07cd402531852537fb109f8dcd63d6627b856087 should fix this
