### ISSUE TITLE
Feature Request: Show location of title in Title Manager

### ISSUE THREAD

**Issue by Crementif** [cemu-project/Cemu#678]
**Who**
This'd be a good issue to be fixed by someone who wants to get involved, but doesn't have much C++ or wxWidgets knowledge. 

**Why**
It's currently hard to know without opening the title entry directory whether it's pulling games/updates/DLCs from the MLC01 path or from the games path. Hence why it'd be a nice QoL improvement.

**How**
The process of fixing this would be adding a new column to the Title Manager which'd show whether the game is located from the MLC01 folder (/"installed") or whether it's found from one of the game paths.

**Extra**
Another task could be seeing how duplicate entries are being treated by the game list, but that can happen later.
  
---
To any (new or existing) developer that might look into this, thanks for wanting to help! Let me know if you need any help or have any questions if I forgot to mention something.

**Comment by RivanParmar** [comment]
Hi, I would like to work on this issue! However, I have a few questions regarding this issue:
- What should be the name of the column?
- What exactly should the column show? (Like only "MLC01" and "Game Path" or something else)

**Comment by Crementif** [comment]
Awesome! For a lot of the design decisions I would just experiment a bit to see what looks best. If you want some guidance/opinions: depending on the column you could go with Installed (Yes/No) or Location (Installed/Game Folders, MLC/Game Path etc.), at least those are some things I was thinking off.

**Comment by RivanParmar** [comment]
I've setup the project as described in the `BUILD.md` file. I've got Visual Studio 2019 with Windows 10 SDK. However, upon building the project I'm getting the following errors:
```
Cemu\build\vcpkg_installed\x64-windows-static\include\fmt\format.h(3548,11): error C2993: 'fmt::v9::detail_exported::fixed_string<Char,N>': is not a valid type for non-type template parameter 'Str'
Cemu\build\vcpkg_installed\x64-windows-static\include\fmt\format.h(4163,61): error C3686: 'operator ""_a': literal operator template must have exactly one template parameter that is a parameter pack
Cemu\build\vcpkg_installed\x64-windows-static\include\fmt\format.h(4163,61): error C3687: 'operator ""_a': literal operator template must have non-type template parameter of type 'char'
```
In total I'm getting 66 errors that are of the same type as above but for different modules. So, could you please tell me on how I can fix these errors?

**Comment by lijunyu-cn** [comment]
For most recent cmake, it generates vs2022 project files by default, so you may use command line like this `cmake -G "Visual Studio 16 2019" -B build/` to generate project files for vs2019.

**Comment by RivanParmar** [comment]
@lijunyu-cn I'm still getting the same errors during build after generating the project files using that command!

**Comment by lijunyu-cn** [comment]
C++20 support needed for compile the project, do you upgrade your vs2019 to newer version? I'm sure there is no error while build with vs2019 newest version 16.11.24.

**Comment by RivanParmar** [comment]
@lijunyu-cn Thanks for helping! The project builds without errors after updating VS 2019 to 16.11.24

**Comment by RivanParmar** [comment]
Here's how it looks with an "Installed" column:
![Title Manager 1](https://user-images.githubusercontent.com/77159650/223205024-b22599ad-3db2-4f87-a525-017d3ab43f9e.png)

And here's with a "Location" column:
![Title Manager](https://user-images.githubusercontent.com/77159650/223205170-0a5fa202-8d46-4aeb-a10c-05a86cabe9c0.png)

Idk why but when I use `entry.path` to show the location of the title, some of the "/" are inverted as seen in the photo above. Also in both the photos, the titles aren't the same which is why the difference. So, now which would you suggest?

And in both the cases I convert the `entry.path` to a string and for the first case I check whether the string contains the "usr/title" folder and show "Yes" or "No" based on it. Therefore, if there is a better way to check it then please do tell me.

**Comment by Crementif** [comment]
Sorry for the late reply. I think including the game paths themselves would too messy, especially since users might not have their folders in a short path. Could you try simply using "MLC Folder"/"Game Folder" for the location?

**Comment by RivanParmar** [comment]
@Crementif You mean to simply show either the name of the game folder/name of MLC folder without the full path?

**Comment by Masamune3210** [comment]
Could just have check boxes, one for mlc and one for loose, and have a right click option or button to open a explorer window to the currently selected title's location

**Comment by Crementif** [comment]
> @Crementif You mean to simply show either the name of the game folder/name of MLC folder without the full path? Something like if it's present in MLC folder then show "mlc01" and if it's not installed then show "Breath of the Wild".

Sorry for the late reply, again, but I meant it just literally. So "Game Paths" (for the ones that are added from the Options->General Settings->Game Paths) or "MLC01" for the non-standard ones. I don't think columns that are dynamically sized work very well in GUI lists and I think it's best to avoid them.

**Comment by RivanParmar** [comment]
Like this? 
![Title Manager 2](https://user-images.githubusercontent.com/77159650/224506643-903ef4dc-8f8f-4f85-afbb-ffd916c31fb6.png)

**Comment by Crementif** [comment]
Yup. Maybe @Exzap can chime in and tell what he likes best. I think the latter is the more informative one, especially in your example where there update is found is found in both the MLC01 and Game Paths, but it might look a bit messier.

If you open up a pull request (I'm assuming you've got some github knowledge), I can check out the code and we can get this merged. Thanks for the work so far with regards to testing the different options!

**Comment by RivanParmar** [comment]
I've opened pull request #697
