### ISSUE TITLE
Fails to compile on Arch with GCC 14.1

### ISSUE THREAD

**Issue by wantija** [cemu-project/Cemu#1196]
### Current Behavior

Arch has GCC 14.1 it their repos now, after a fullsystem upgrade, cemu does not compile.

### Expected Behavior

Cemu compiles from latest git.

### Steps to Reproduce

Compile cemu from source/AUR with makepkg -si

### Logs (Optional)

[ 89%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/DumpCtrl.cpp.o
[ 89%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/DisasmCtrl.cpp.o
[ 89%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/DumpWindow.cpp.o
In file included from /home/anon/data/git/cemu-git/src/cemu/src/gui/../gui/ChecksumTool.h:5,
                 from /home/anon/data/git/cemu-git/src/cemu/src/gui/ChecksumTool.cpp:1:
/usr/include/rapidjson/document.h: In member function ‘rapidjson::GenericStringRef<CharType>& rapidjson::GenericStringRef<CharType>::operator=(const rapidjson::GenericStringRef<CharType>&)’:
/usr/include/rapidjson/document.h:319:82: error: assignment of read-only member ‘rapidjson::GenericStringRef<CharType>::length’
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~~^~~~~~~~~~~~
In file included from /home/anon/data/git/cemu-git/src/cemu/src/gui/../gui/ChecksumTool.h:5,
                 from /home/anon/data/git/cemu-git/src/cemu/src/gui/components/wxDownloadManagerList.cpp:21:
/usr/include/rapidjson/document.h: In member function ‘rapidjson::GenericStringRef<CharType>& rapidjson::GenericStringRef<CharType>::operator=(const rapidjson::GenericStringRef<CharType>&)’:
/usr/include/rapidjson/document.h:319:82: error: assignment of read-only member ‘rapidjson::GenericStringRef<CharType>::length’
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~~^~~~~~~~~~~~
In file included from /home/anon/data/git/cemu-git/src/cemu/src/gui/../gui/ChecksumTool.h:5,
                 from /home/anon/data/git/cemu-git/src/cemu/src/gui/components/wxTitleManagerList.cpp:25:
/usr/include/rapidjson/document.h: In member function ‘rapidjson::GenericStringRef<CharType>& rapidjson::GenericStringRef<CharType>::operator=(const rapidjson::GenericStringRef<CharType>&)’:
/usr/include/rapidjson/document.h:319:82: error: assignment of read-only member ‘rapidjson::GenericStringRef<CharType>::length’
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~~^~~~~~~~~~~~
[ 89%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/ModuleWindow.cpp.o
[ 89%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/RegisterCtrl.cpp.o
[ 90%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/debugger/RegisterWindow.cpp.o
make[2]: *** [src/gui/CMakeFiles/CemuGui.dir/build.make:157: src/gui/CMakeFiles/CemuGui.dir/ChecksumTool.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/gui/CMakeFiles/CemuGui.dir/build.make:189: src/gui/CMakeFiles/CemuGui.dir/components/wxDownloadManagerList.cpp.o] Error 1
make[2]: *** [src/gui/CMakeFiles/CemuGui.dir/build.make:253: src/gui/CMakeFiles/CemuGui.dir/components/wxTitleManagerList.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:463: src/gui/CMakeFiles/CemuGui.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by GaryOderNichts** [comment]
This is a bug in rapidjson which was patched in the [Arch package](https://gitlab.archlinux.org/archlinux/packaging/packages/rapidjson/-/commit/20e6c15a0fd8276e9c9200e337db6374695dc68b). Make sure to update your packages and try building Cemu again.

**Comment by wantija** [comment]
that seems to have fixed it, thanks!

**Comment by nuclearpidgeon** [comment]
For reference as this issue was the first thing that came up when I googled for this "assignment of read-only member" issue - it is tracked in the rapidjson project under Tencent/rapidjson#2277 . It seems a fix has been merged as of 2016(!) but there has still not been a new release with the fix in it...

**Comment by Ammar-Sadaoui** [comment]
> For reference as this issue was the first thing that came up when I googled for this "assignment of read-only member" issue - it is tracked in the rapidjson project under Tencent/rapidjson#2277 . It seems a fix has been merged as of 2016(!) but there has still not been a new release with the fix in it...

thanks for showing me this repo 

It's funny that Dev refused to release new version. Instead, he suggested forking the project
